language: node_js
cache:
  yarn: true
branches:
  only:
    - master
before_script:
  - yarn lint
  - yarn ts-check
  - yarn test --passWithNoTests
script:
  - yarn build
  - echo "efreitasn.dev" > public/CNAME
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true